version: '3.7'
services:
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass 123456 --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - /opt/docker-data/redis/master/data:/data
  proxy_pool:
    image: jhao104/proxy_pool
    depends_on:
      - redis
    restart: always
    ports:
    - 5010:5010
    environment:
      db_type: REDIS
      db_host: redis
      db_port: 6379
      db_password: 123456