version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      #      KAFKA_ADVERTISED_HOST_NAME: PLAINTEXT://192.168.0.161:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://139.9.218.43:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock