version: '2'
services:
  zoo1:
    image: zookeeper
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo1data:/data
    networks:
      - cluster
  zoo2:
    image: zookeeper
    container_name: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    volumes:
      - zoo2data:/data
    networks:
      - cluster
  zoo3:
    image: zookeeper
    container_name: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    volumes:
      - zoo3data:/data
    networks:
      - cluster
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      ## 修改:宿主机IP
      KAFKA_ADVERTISED_HOST_NAME: 192.168.30.107
      ## 修改:宿主机映射port
      KAFKA_ADVERTISED_PORT: 9092
      ## 绑定发布订阅的端口。修改:宿主机IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.30.107:9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./kafka/kafka1/docker.sock:/var/run/docker.sock
      - kafka1data:/kafka
    networks:
      - cluster
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - 9093:9092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.30.107
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.30.107:9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./kafka/kafka2/docker.sock:/var/run/docker.sock
      - kafka2data:/kafka
    networks:
      - cluster
  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - 9094:9092
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.30.107
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.30.107:9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
    volumes:
      - ./kafka/kafka3/docker.sock:/var/run/docker.sock
      - kafka3data:/kafka
    networks:
      - cluster
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zoo2:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    volumes:
      - kafkamanagerdata:/opt
    networks:
      - cluster


networks:
  cluster:
    driver: bridge

volumes:
  zoo1data:
    driver: local
  zoo2data:
    driver: local
  zoo3data:
    driver: local
  kafka1data:
    driver: local
  kafka2data:
    driver: local
  kafka3data:
    driver: local
  kafkamanagerdata:
    driver: local